### ISSUE TITLE
Source archives are empty?

### ISSUE THREAD

**Issue by vaizki** [befinitiv/rpi_wifibroadcast_image_builder#1]
Great project and very interested to see what you have done, however the source .zip and .tar.gz files are empty?

Could you just put them up as a normal git repo instead of archives?

**Comment by befinitiv** [comment]
hi

you find the sources here:
https://bitbucket.org/befi/rpi_wifibroadcast_image_builder

the reason for this is that i am a bitbucket user but the releases there
are terrible. so i use github for releases and bitbucket for source code.
Am 18.12.2015 11:23 schrieb "vaizki" notifications@github.com:
